routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('restaurant', 'RestaurantController');
Route::get('restaurant/destroy/{id}', ['as' => 'restaurant/destroy', 'uses' => 'RestaurantController@destroy']);
Route::post('restaurant/show', ['as' => 'restaurant/show', 'uses' => 'RestaurantController@show'] );
Auth::routes();

Route::resource('reservation', 'ReservationController');
Route::get('reservation/destroy/{id}', ['as' => 'reservation/destroy', 'uses' => 'ReservationController@destroy']);
Route::post('reservation/show', ['as' => 'reservation/show', 'uses' => 'ReservationController@show'] );
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/reservation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class reservation extends Model
{
    Protected $table = 'reservations';
    protected $fillable = ['datere', 'restaurant'];
    protected $guarded = ['id'];
}

app/Models/restaurant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class restaurant extends Model
{
    Protected $table = 'restaurants';
    protected $fillable = ['name', 'description', 'adress', 'city', 'photo'];
    protected $guarded = ['id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ReservationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Reservation as Reservation;

class ReservationController extends Controller
{
    public function index()
	{
		$reservations = Reservation::all();
		return \View::make('reservation/list', compact('reservations'));

	}
	public function store(Request $request)
	{
		$reservation = new Reservation;
	    $reservation->datere = $request->datere;
	    $reservation->restaurant = $request->restaurant;
	    $reservation->save();
	    return redirect('reservation');
	}

	public function create()
	{
		return \View::make('reservation/new');
	}

	public function edit($id)
	{
		$reservation = Reservation::find($id);
		return \View::make('reservation/update', compact('reservation'));
	}

	public function update($id, Request $request)
	{
		$reservation = Reservation::find($id);
		$reservation->datere = $request->datere;
		$reservation->restaurant = $request->restaurant;
		$reservation->save();
		return redirect('reservation');
	}

	public function show(Request $request)
	{
		$reservations = Reservation::where('restaurant','like','%'.$request->restaurant.'%')->get();
		return \View::make('reservation/list' ,compact('reservations'));
	}

	public function destroy($id)
	{
		$reservation = Reservation::find($id);
		$reservation->delete();
		return redirect()->back();
	}
}

app/Http/Controllers/RestaurantController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Restaurant as Restaurant;

class RestaurantController extends Controller
{
    public function index()
	{
		$restaurants = Restaurant::all();
		return \View::make('restaurants/list', compact('restaurants'));
	}
	public function store(Request $request)
	{
		$file = $request->photo;
        $path = public_path().'/images/';
        $fileName = $file->getClientOriginalName();

      	$file->move($path, $fileName);

		$restaurant = new Restaurant;
	    $restaurant->name = $request->name;
	    $restaurant->description = $request->description;
	    $restaurant->adress = $request->adress;
	    $restaurant->city = $request->city;
	    $restaurant->photo = $fileName;
	    $restaurant->save();
	    return redirect('restaurant');
	}

	public function create()
	{
		return \View::make('restaurants/new');
	}

	public function edit($id)
	{
		$restaurant = Restaurant::find($id);
		return \View::make('restaurants/update', compact('restaurant'));
	}

	public function update($id, Request $request)
	{
		$restaurant = Restaurant::find($id);
		$restaurant->name = $request->name;
		$restaurant->description = $request->description;
		$restaurant->adress = $request->adress;
	    $restaurant->city = $request->city;
	   // $restaurant->photo = $request->photo;
		$restaurant->save();
		return redirect('restaurant');
	}

	public function show(Request $request)
	{
		if ($request->city != null) {
			$restaurants = Restaurant::where('city','=',$request->city)->get();
		}else{
			$restaurants = Restaurant::where('name','like','%'.$request->name.'%')->get();
		}
		
		return \View::make('restaurants/list' ,compact('restaurants'));
	}

	public function destroy($id)
	{
		$restaurant = Restaurant::find($id);
		$restaurant->delete();
		return redirect()->back();
	}
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/reservation/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!! Form::open(['route' => 'reservation/show', 'method' => 'post', 'novalidate', 'class' => 'form.inline' ]) !!}
					<div class="form-group" >
						<label>Restaurante</label>
						<input type="text" name="restaurant" class="form-control">
					</div>
					<div class="form-group" >
						<button class="btn btn-default">Buscar</button>
						<a href="{{ route('reservation.index') }}" class="btn btn-success">Todos</a>
						<a href="{{ route('reservation.create') }}" class="btn btn-success">Crear</a>
					</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-condensed table-striped table-bordered" >
					<thead>
						<tr>
							<th>Dia de la reserva</th>
							<th>Restaurante</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($reservations as $reservation)
							<tr>
								<td>{{ $reservation->datere }}</td>
								<td>{{ $reservation->restaurant }}</td>
								<td>
									<a class="btn btn-primary btn-xs" href="{{ route('reservation.edit',['id' => $reservation->id]) }}">Editar</a>
									<a class="btn btn-danger btn-xs" href="{{ route('reservation/destroy', ['id' => $reservation->id]) }}">Borrar</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/reservation/new.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::open(['route' => 'reservation.store', 'method' => 'post', 'novalidate' ]) !!}
					<div class="form-group">
						<label>Dia de la reserva</label>
						<input type="date" name="datere" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Restaurante</label>
						<input type="text" name="restaurant" class="form-control" required>
					</div>
					<div class="form-group">
						<button type="subit" class="btn btn-success">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection

resources/views/reservation/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::model($movie, ['route' => ['movie.update', $movie->id], 'method' => 'put', 'novalidate' ]) !!}
					<div class="form-group">
						<label>Dia de la reserva</label>
						<input type="date" name="datere" class="form-control" value="{{ $movie->datere }}" required>
					</div>
					<div class="form-group">
						<label>Restaurante</label>
						<input type="text" name="restaurant" class="form-control" value="{{ $movie->restaurant }}" required>
					</div>
					<div class="form-group">
						<button type="subit" class="btn btn-success">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection

resources/views/restaurants/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!! Form::open(['route' => 'restaurant/show', 'method' => 'post','enctype' => 'multipart/form-data', 'novalidate', 'class' => 'form.inline' ]) !!}
					<div class="row" >
						<div class="col-md-6" >
							<div class="form-group" >
								<label>Nombre</label>
								<input type="text" name="name" class="form-control">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group" >
								<label>Ciudad</label>
								<input type="text" name="city" class="form-control">
							</div>
						</div>
					</div>
					<div class="form-group" >
						<button class="btn btn-default">Buscar</button>
						<a href="{{ route('restaurant.index') }}" class="btn btn-success">Todos</a>
						<a href="{{ route('restaurant.create') }}" class="btn btn-success">Crear</a>
					</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-condensed table-striped table-bordered" >
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Description</th>
							<th>Direccion</th>
							<th>Ciudad</th>
							<th>Foto</th>
							<th>Opcion</th>
						</tr>
					</thead>
					<tbody>
						@foreach($restaurants as $restaurant)
							<tr>
								<td>{{ $restaurant->name }}</td>
								<td>{{ $restaurant->description }}</td>
								<td>{{ $restaurant->adress }}</td>
								<td>{{ $restaurant->city }}</td>
								<td><img src="{{ asset('images/'.$restaurant->photo) }}" height="40" width="30"></td>
								<td>
									<a class="btn btn-primary btn-xs" href="{{ route('restaurant.edit',['id' => $restaurant->id]) }}">Editar</a>
									<a class="btn btn-danger btn-xs" href="{{ route('restaurant/destroy', ['id' => $restaurant->id]) }}">Borrar</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/restaurants/new.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::open(['route' => 'restaurant.store', 'method' => 'post','files' => true, 'novalidate' ]) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Descripcion</label>
						<input type="text" name="description" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Direccion</label>
						<input type="text" name="adress" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Ciudad</label>
						<input type="text" name="city" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Foto</label>
						<input type="file" name="photo" class="form-control" required>
					</div>
					<div class="form-group">
						<button type="subit" class="btn btn-success">Registar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection

resources/views/restaurants/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::model($restaurant, ['route' => ['restaurant.update', $restaurant->id], 'method' => 'put', 'files' => true, 'novalidate' ]) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" value="{{ $restaurant->name }}" >
					</div>
					<div class="form-group">
						<label>Descripcion</label>
						<input type="text" name="description" class="form-control" value="{{ $restaurant->description }}" >
					</div>
					<div class="form-group">
						<label>Direccion</label>
						<input type="text" name="adress" class="form-control" value="{{ $restaurant->adress }}" >
					</div>
					<div class="form-group">
						<label>Ciudad</label>
						<input type="text" name="city" class="form-control" value="{{ $restaurant->city }}" >
					</div>
					<!--<div class="form-group">
						<label>Foto</label>
						<input type="file" name="photo" class="form-control" value="{{ $restaurant->photo }}" >
					</div>-->
					<div class="form-group">
						<button type="subit" class="btn btn-success">Actualizar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection